# Generated by Django 3.2.9 on 2021-11-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=80)),
                ('city', models.CharField(max_length=80)),
                ('postal_abbr', models.CharField(choices=[('MX', 'Mexico'), ('AL', 'Alabama'), ('NE', 'Nebraska'), ('AK', 'Alaska'), ('NV', 'Nevada'), ('AZ', 'Arizona'), ('NH', 'New Hampshire'), ('AR', 'Arkansas'), ('NJ', 'New Jersey'), ('CA', 'California'), ('NM', 'New Mexico'), ('CO', 'Colorado'), ('NY', 'New York'), ('CT', 'Connecticut'), ('NC', 'North Carolina'), ('DE', 'Delaware'), ('ND', 'North Dakota'), ('DC', 'District of Columbia'), ('OH', 'Ohio'), ('FL', 'Florida'), ('OK', 'Oklahoma'), ('GA', 'Georgia'), ('OR', 'Oregon'), ('HI', 'Hawaii'), ('PA', 'Pennsylvania'), ('ID', 'Idaho'), ('PR', 'Puerto Rico'), ('IL', 'Illinois'), ('RI', 'Rhode Island'), ('IN', 'Indiana'), ('SC', 'South Carolina'), ('IA', 'Iowa'), ('SD', 'South Dakota'), ('KS', 'Kansas'), ('TN', 'Tennessee'), ('KY', 'Kentucky'), ('TX', 'Texas'), ('LA', 'Louisiana'), ('UT', 'Utah'), ('ME', 'Maine'), ('VT', 'Vermont'), ('MD', 'Maryland'), ('VA', 'Virginia'), ('MA', 'Massachusetts'), ('VI', 'Virgin Islands'), ('MI', 'Michigan'), ('WA', 'Washington'), ('MN', 'Minnesota'), ('WV', 'West Virginia'), ('MS', 'Mississippi'), ('WI', 'Wisconsin'), ('MO', 'Missouri'), ('WY', 'Wyoming'), ('MT', 'Montana')], default='MX', max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule_open', models.TimeField()),
                ('schedule_close', models.TimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ristorante.address')),
            ],
        ),
    ]
